# EMS 575X Sputter Coater

Review the principles of [sputtering deposition](https://www.emsdiasum.com/microscopy/technical/datasheet/sputter_coating.aspx).

### History:
- initial: 2/28/2013
- update: 5/28/2015


## Warnings

- make sure chamber seal is good 
- make sure gas lines are open and at correct pressures
- remove FTM cover
- allow system to cool with fan
- monitor plasma


## Deposition

1.	Check that the tubes from Nitrogen and Argon gas tanks are attached to the appropriate inputs on the back of the [EMS575X unit.](https://www.emsdiasum.com/microscopy/) **Open the vales on both tanks and confirm that the tanks are not empty.** The regulated pressure on each tank should read between 10 psi.
2.	Make sure that the vacuum pump is properly attached to the sputter system unit and turned on. 
3.	**Put on gloves before touching anything inside the sputter deposition chamber.**
4.	Open the top of the EMS575X unit and ensure that the appropriate targets are mounted. If not, unscrew the four screws holding the target mount and insert the desired target, taking note of which position it is in (the left side is target A, the right side is target B). When changing or moving targets, label which target is in which position on the paper mounted on the wall above the unit. Targets are stored in the drawer labeled `Sputter Coater Components`, directly beneath the sputter unit. For more information regarding target insertion/removal, see the EMS575X instruction manual.
5.	Confirm that the sample plate is covered with Al foil. The foil can be replaced if it contains significant amounts of deposited materials.  
6.	Place the samples on the center of the sample plate, with shadow masks if desired.
7.	Turn on the unit using the black power switch on the back right hand side of the unit.
8.	**Remove the FTM (film thickness monitor) cover.** This is the circular metal cap that covers the FTM. 
9.	Close the top of the unit.
10.	Using the buttons on the front of the unit, cycle through the options until the desired settings are reached.
11.	When the settings are correct, press the start button. The screen will display the important final settings once more. If the settings are correct, press the start button again.
12.	If at anytime during the sputtering process a problem occurs, the system can be stopped manually by pressing the stop button on the front panel.
13.	During the target cleaning sequence and the sputter coating sequences, the cylindrical metal valve on the back left side of the unit can be used to adjust the Argon pressure inside the unit. Carefully adjust this valve during the deposition until the plasma (the purple glow inside the chamber) reaches the greatest intensity. This will improve the deposition rate.
14.	The deposition occurs in coating sequences of 5 minutes each (to prevent overheating).
15.	After the desired thickness has been reached, the system will end the sequence and the chamber will be vented.
16.	When the screen indicates that the venting process has terminated, open the top of the system and remove the samples. Replace the FTM cover and close the unit.
17.	**Close the valves to the Nitrogen and Argon tanks, and turn off the pump.**
18.	**Leave the unit on until the top metal lid of the unit has cooled to room temperature.** After cooling, turn the unit off using the power switch.
